app-name: VF Cash Helper
package-name: com.example.vfcashhelper
version: 1.0.0
description: تطبيق لتحويل فودافون كاش وإدارة جهات الاتصال
icon: assets/icon.png  # يجب وضع أيقونة في مجلد assets

requirements:
  - python==3.9
  - flet>=0.22.0
  - SpeechRecognition>=3.10.0
  - PyAudio>=0.2.14

include:
  - main.py
  - assets/
  - contacts.db  # إذا كنت تريد تضمين قاعدة بيانات ابتدائية

android:
  permissions:
    - android.permission.INTERNET
    - android.permission.RECORD_AUDIO
  orientation: portrait
  enable-androidx: true
  signing-config:
    keystore: my-release-key.keystore
    keystore-password: "password"
    alias: "my-alias"
    alias-password: "password"

ios:
  requirements: null
  orientation: portrait

windows:
  requirements: null
  console: true

linux:
  requirements: null
  console: true

macos:
  requirements: null
  console: true

web:
  requirements: null
  port: 8080
